# Generated by Django 5.2.8 on 2025-12-01 19:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trigger', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstanciaZap',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome_operador', models.CharField(help_text='Ex: Atendente Maria', max_length=100)),
                ('numero_telefone', models.CharField(help_text='Apenas referência visual', max_length=20)),
                ('instancia_id', models.CharField(help_text='ID da Instância na UazAPI', max_length=100)),
                ('token', models.CharField(help_text='Token da Instância', max_length=255)),
                ('conectado', models.BooleanField(default=False)),
                ('ultima_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Instância WhatsApp',
                'verbose_name_plural': 'Instâncias WhatsApp',
            },
        ),
        migrations.AlterField(
            model_name='contato',
            name='nome',
            field=models.CharField(default='Desconhecido', max_length=150),
        ),
    ]
