# Generated by Django 5.2.8 on 2026-01-29 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trigger', '0002_instanciazap_alter_contato_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instanciazap',
            name='instancia_id',
            field=models.CharField(help_text='r92424209e72cb5', max_length=100),
        ),
        migrations.AlterField(
            model_name='instanciazap',
            name='token',
            field=models.CharField(help_text='c3f4ee8f-f203-4482-9b38-a5c218c88617', max_length=255),
        ),
    ]
